services:
  iperfclient1:
    build:
      context: .
      dockerfile: dev-IperfClient1/Dockerfile   
    container_name: IperfClient1
    restart: unless-stopped    
    volumes:
      - ./dev-IperfClient1/etc/wireguard:/etc/wireguard  
    cap_add:
      - NET_ADMIN
      - SYS_MODULE     
    tty: true
    stdin_open: true
    network_mode: host