services:
  iperfclient1:
    build:
      context: .
      dockerfile: dev-IperfClient1/Dockerfile   
    # image: felixfischer/wireguard:latest
    container_name: IperfClient1
    restart: unless-stopped    
    volumes:
      - ./dev-IperfClient1/etc/wireguard:/etc/wireguard  
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1      
    tty: true
    stdin_open: true  
    networks:      
      vpn-c-net1:
        ipv4_address: 192.168.151.51       
  
# sudo docker stop IperfClient1
# sudo docker rm IperfClient1

# docker exec -it IperfClient1 bash
# iperf3 -c 192.168.110.100 -t 1
# docker exec IperfClient1 iperf3 -c 192.168.110.100 -t 1
# sudo docker exec IperfClient1 ping 172.16.10.200
#######################################################
networks:
  vpn-c-net1:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.151.0/24
